# untested since no access to azure devops is available
trigger:
  branches:
    include:
      - master
      - develop

pr:
  branches:
    include:
      - master
      - develop

variables:
  buildConfiguration: 'Release'
  projectPath: 'Person.Presentation.RestAPI/Person.Presentation.RestAPI.csproj'
  publishDir: '$(Build.ArtifactStagingDirectory)/publish'

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '9.0.x'
    includePreview: false

- task: Cache@2
  displayName: 'Cache NuGet packages'
  inputs:
    key: 'nuget | "$(Agent.OS)" | **/packages.lock.json'
    path: $(NUGET_PACKAGES)
    restoreKeys: |
      nuget | "$(Agent.OS)"

- script: dotnet restore "$(projectPath)"
  displayName: 'dotnet restore'

- script: dotnet build "$(projectPath)" --configuration $(buildConfiguration) --no-restore
  displayName: 'dotnet build (MSBuild)'

- script: dotnet publish "$(projectPath)" --configuration $(buildConfiguration) --no-build --output "$(publishDir)"
  displayName: 'dotnet publish (produce artifact)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact'
  inputs:
    PathtoPublish: '$(publishDir)'
    ArtifactName: 'api-publish'
    publishLocation: 'Container'